#!/bin/bash
rm -rf /tmp/.iiim-$USER
docker run -d --net=none -v /tmp:/tmp -v /home:/home  -v /run:/run \
  -e LC_CTYPE=ja_JP.utf-8 -e LC_COLLATE=ja_JP.utf-8 \
  -e DISPLAY=$DISPLAY -e HOME=$HOME \
  -e XDG_SEAT=$XDG_SEAT \
  -e XDG_SESSION_ID=$XDG_SESSION_ID \
  -e XDG_SESSION_COOKIE=$XDG_SESSION_COOKIE \
  -e XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
  -e HTT_DISABLE_STATUS_WINDOW=t \
  -e HTT_USES_LINUX_XKEYSYM=t \
  -e HTT_IGNORES_LOCK_MASK=t \
  -e HTT_GENERATES_KANAKEY=t \
  -e JS_FEEDBACK_CONVERT=t \
  -e USER=$USER -e LOGNAME=$LOGNAME \
  -h `hostname` -u $USER local/atokx3 \
  bash -c 'xauth list :0; env; /usr/bin/iiimx -iiimd; trap exit TERM INT; sleep infinity'
sleep 5
(
  cd /tmp/.iiim-$USER
  test -r :0.0 && ln -s :0.0 :0
)
